version: '3.9'

services:
    web:
        image: php-apache-7.0.8
        ports:
            - 8090:80
        volumes:
            - ".:/var/www/html/"
        restart: on-failure
        deploy:
            labels:
                com.example.description: "apache web server with php and mysqli extenstion"
            mode: replicated
            replicas: 2    
            resources:
                limits:
                    cpus: '0.2'
                    memory: 50M
                reservations:
                    cpus: '0.1'
                    memory: 20M
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        networks:
            app_net:
                ipv4_address: 10.0.22.10
    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql-volume:/var/lib/mysql
        restart: always
        environment:
            TZ: "Malaysia/Kuala lumpur"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "Abcd4321"
            MYSQL_USER: 'admin1'
            MYSQL_PASSWORD: '2JOH0pqIvXqeOq5t'
            MYSQL_DATABASE: 'admin'
        deploy:
            mode: replicated
            replicas: 2
#            resources:
                # limits:
                #     cpus: '0.2'
                #     memory: 50M
                # reservations:
                #     cpus: '0.1'
                #     memory: 20M
        networks:
            app_net:
                ipv4_address: 10.0.22.11
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - database
        ports:
            - '8091:80'
        deploy:
            resources:
                limits:
                    cpus: '0.2'
                    memory: 50M
                reservations:
                    cpus: '0.1'
                    memory: 20M
        #mode: replicated
        #replicas: 2
        restart: on-failure
        networks:
            app_net:
                ipv4_address: 10.0.22.12

volumes:
    mysql-volume:
networks:
    app_net:
        ipam:
            driver: overlay
            config:
                - subnet: "10.0.22.0/24"
