version: '3.3'

services:
    web:
        container_name: admin_php-apache
        image: php:8.0.7-apache
        ports:
            - 8090:80
        volumes:
            - ".:/var/www/html/"
    db:
        container_name: admin_mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql-volume:/var/lib/mysql
        environment:
            TZ: "Malaysia/Kuala lumpur"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "Abcd4321"
            MYSQL_USER: 'admin1'
            MYSQL_PASSWORD: '2JOH0pqIvXqeOq5t'
            MYSQL_DATABASE: 'admin'
    phpmyadmin:
        container_name: admin_phpmyadmin
        image: phpmyadmin/phpmyadmin
        links:
            - 'db:db'
        ports:
            - '8091:80'
volumes:
    mysql-volume:

